apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
        - name: quotes-app
          image: gcr.io/$GCP_PROJECT/$IMAGE_NAME:$CIRCLE_TAG
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/quotes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0